### ISSUE TITLE
Links to zipfiles are broken

### ISSUE THREAD

**Issue by sypets** [rackerlabs/docs-style-guide#34]
The section [Icons, Stencils & Shapes](https://developer.rackspace.com/docs/style-guide/screenshots/diagram-guidelines/#before-you-create-a-diagram) contains two broken links to zipfiles:

* https://github.com/rackerlabs/docs-rackspace/blob/master/doc/style-guide/images/zip/ProductIcons.zip
* https://github.com/rackerlabs/docs-rackspace/blob/master/doc/style-guide/images/zip/RackspaceDiagramIcons.zip

**Comment by cyrichardson** [comment]
@sypets i’ll look into this tomorrow and see if I can locate the zip files.  Thanks for opening this issue. Stay tuned!

**Comment by cyrichardson** [comment]
@sypets I updated the link to go to the right place. They links will now go a spot on GitHub to pick up the zip files, which you can save and open on your local drive.

Again, thanks so much for reporting this issues. I really appreciate it!

**Comment by cyrichardson** [comment]
Closed this issue by updating the links in master.
